name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    env:
      PROJECT: SwiftyColor.xcodeproj
      SCHEME: SwiftyColor-Package
      CODECOV_PACKAGE_NAME: SwiftyColor
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

          - sdk: macosx
            destination: arch=x86_64

    steps:
    - uses: actions/checkout@v1

    - name: List SDKs and Devices
      run: xcodebuild -showsdks; instruments -s

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj --enable-code-coverage

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -X xcodeplist \
          -J "$CODECOV_PACKAGE_NAME"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
