name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator12.2
            destination: platform=iOS Simulator,name=iPhone XS,OS=12.2

          - sdk: macosx10.14
            destination: arch=x86_64

    steps:
    - uses: actions/checkout@v1

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj --enable-code-coverage

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        PROJECT: SwiftyColor.xcodeproj
        SCHEME: SwiftyColor-Package
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -X xcodeplist \
          -J SwiftyColor \
          -t 2e3ef5e8-ca59-4831-bfcb-267ca5ce8f75
